# Time
PHYSICS_FPS = 50
MAX_STEPS = 5000
ACTION_REPEAT = 2

# Track
TRACK_RADIUS = 10.0
TRACK_CENTER_X = 0.0
TRACK_CENTER_Y = 0.0
TRACK_HALF_WIDTH = 2.0
NUM_TILES = 100

# Car
MAX_SPEED = 30.0
START_DIRECTION = 0.0

# Rendering
SCREEN_SIZE = (800, 800)
ZOOM = 20.0

# Reward
NEW_TILE_REWARD = 0.01
OFF_TRACK_PENALTY = 1.0
LAP_BONUS = 1.0
COLLISION_PENALTY = 1.0
GAMMA_DISCOUNT = 0.9995

# Set to a number n for n laps max, None for endurance mode
MAX_LAPS = None

# Agents
NUM_AGENTS = 1